
package br.com.webservice.soa.client.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloImplService", targetNamespace = "http://impl.soa.webservice.com.br/", wsdlLocation = "http://localhost:54321/hello?wsdl")
public class HelloImplService
    extends Service
{

    private final static URL HELLOIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.webservice.soa.client.wsdl.HelloImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.webservice.soa.client.wsdl.HelloImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:54321/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:54321/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloImplService() {
        super(HELLOIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.soa.webservice.com.br/", "HelloImplService"));
    }

    /**
     * 
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloImplPort")
    public Hello getHelloImplPort() {
        return super.getPort(new QName("http://impl.soa.webservice.com.br/", "HelloImplPort"), Hello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloImplPort")
    public Hello getHelloImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.soa.webservice.com.br/", "HelloImplPort"), Hello.class, features);
    }

}
