
package br.com.webservice.soa.client.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://infra.soa.webservice.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloTo", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.SayHelloTo")
    @ResponseWrapper(localName = "sayHelloToResponse", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.SayHelloToResponse")
    public String sayHelloTo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToUser", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.SayHelloToUser")
    @ResponseWrapper(localName = "sayHelloToUserResponse", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.SayHelloToUserResponse")
    public String sayHelloToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.webservice.soa.client.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserFromEmail", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.GetUserFromEmail")
    @ResponseWrapper(localName = "getUserFromEmailResponse", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.GetUserFromEmailResponse")
    public User getUserFromEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.webservice.soa.client.wsdl.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://infra.soa.webservice.com.br/", className = "br.com.webservice.soa.client.wsdl.GetAllUsersResponse")
    public List<User> getAllUsers();

}
